In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("zillow_final.csv")

In [17]:
df.columns

Index(['price', 'bed', 'bath', 'living', 'lot_sqft', 'lot_living', 'bed_bath',
       'type_condo', 'type_manufactured', 'type_multi', 'type_single',
       'type_townhouse', 'lat', 'long', 'income', 'poverty', 'unemployment',
       'pop', 'bachelor', 'rent', 'area_home_value', 'owner_occ',
       'pop_density', 'risk_overall', 'risk_loss', 'risk_social',
       'risk_resilience', 'risk_fire', 'risk_earthquake', 'risk_heat',
       'dist_city', 'dist_airport', 'dist_coast'],
      dtype='str')

In [37]:
for col in [
    "income",
    "poverty",
    "unemployment",
    "bachelor",
    "rent",
    "area_home_value",
    "owner_occ"
]:
    print(col, df[col].nunique())

income 540
poverty 565
unemployment 556
bachelor 566
rent 440
area_home_value 505
owner_occ 564

In [31]:
df.head(5)

,price,bed,bath,lot_sqft,lot_living,lat,long,income,poverty,unemployment,...,rent,area_home_value,owner_occ,pop_density,risk_fire,risk_earthquake,risk_heat,dist_city,dist_airport,dist_coast
0,4980000.0,4.0,5.0,4922.000,4126.0,34.100803,-118.380570,107787.0,0.081878,0.054152,...,2217.0,709500.0,0.694277,1022.231475,73.920540,94.138632,8.354783,13.715619,17.888756,13.623171
1,1215000.0,3.0,2.0,7840.800,1825.0,34.180298,-118.642500,107787.0,0.081878,0.054152,...,2217.0,709500.0,0.694277,1022.231475,18.467649,89.615069,13.904381,39.379252,34.192540,22.666476
2,2629000.0,4.0,4.0,43381.404,3019.0,34.112854,-118.433876,107787.0,0.081878,0.054152,...,2217.0,709500.0,0.694277,1022.231475,98.160370,93.614213,13.158396,18.768005,19.185657,11.646300
4,849000.0,2.0,2.0,5002.000,1154.0,33.713604,-118.291880,107787.0,0.081878,0.054152,...,2217.0,709500.0,0.694277,1022.231475,0.000000,87.909814,8.907717,37.911992,27.545766,35.124601
5,949000.0,3.0,2.0,9857.628,2158.0,34.067300,-118.172520,107787.0,0.081878,0.054152,...,2217.0,709500.0,0.694277,1022.231475,78.948307,99.857301,43.449402,6.768662,25.856140,29.839640

In [19]:
df = df[df["type_single"] == True]

In [20]:
print(len(df))

3254

In [ ]:
df["lot_living"] = df["living"]

In [22]:
cols_to_drop = [
    # target cũ nếu không dùng
    "type_condo",
    "type_manufactured",
    "type_multi",
    "type_single",
    "type_townhouse",

    # dễ gây trùng lặp thông tin
    "pop",
    "risk_overall",
    "bed_bath",
    "risk_loss",
    "risk_social",
    "risk_resilience",
    "living"
    
]

df = df.drop(columns=cols_to_drop)

In [27]:
print(len(df[df["bed"] == 0]))
print(len(df[df["bath"] == 0]))
print(len(df[df["lot_sqft"] == 0]))
print(len(df[df["lot_living"] == 0]))
print(len(df[df["price"] == 0]))

0
0
0
0
0

In [26]:
import numpy as np
df.loc[df["lot_sqft"] == 0, "lot_sqft"] = np.nan
df = df.dropna(
    subset=[
        "lot_sqft"
    ]
)

In [30]:
df.nsmallest(
    10,
    "lot_living"
)[[ "lot_sqft", "lot_living"]]

       lot_sqft  lot_living
1370   2178.000       396.0
2457  10018.800       412.0
2421   7840.800       420.0
196    2848.824       436.0
2957   7205.000       440.0
2962   8768.000       468.0
1721   7840.800       470.0
1599   1742.400       472.0
657    2475.000       475.0
2855   5100.000       480.0

In [34]:
df = df[df["lot_sqft"] < 1_000_000]

In [35]:
print(len(df))

3236

In [32]:
df.to_csv("zillow_final2.csv")